# Generated by Django 5.0.4 on 2024-04-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contacts',
            field=models.CharField(default='похоже, тут ничего нет...', max_length=250),
        ),
    ]
