# Generated by Django 5.0.4 on 2024-04-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='passengers',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.passenger'),
        ),
    ]
