# Generated by Django 5.0.4 on 2024-04-24 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passenger_passengers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
