# Generated by Django 5.0.4 on 2024-04-25 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_passengers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contacts',
        ),
    ]
