# Generated by Django 5.0.4 on 2024-04-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_passenger_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_of_service', models.CharField(choices=[('Э', 'Эконом'), ('К', 'Комфорт'), ('Б', 'Бизнес'), ('П', 'Первый класс')], max_length=1)),
                ('luggage', models.BooleanField(default=False)),
            ],
        ),
    ]
