# Generated by Django 5.0.4 on 2024-04-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_airport_remove_tickets_class_of_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightclassinfo',
            name='seats_number',
            field=models.IntegerField(default=0),
        ),
    ]
