# Generated by Django 5.0.4 on 2024-05-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_flight_arrival_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.CharField(default='Unknown Airline', max_length=100),
        ),
    ]
