# Generated by Django 5.0.4 on 2024-05-02 09:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_flight_airline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('luggage_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('luggage', models.BooleanField(default=False)),
                ('service_class', models.CharField(choices=[('economy', 'Эконом'), ('comfort', 'Комфорт'), ('business', 'Бизнес'), ('first_class', 'Первый класс')], max_length=20)),
                ('booking_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='main.flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='main.passenger')),
            ],
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
    ]
