# Generated by Django 5.0.4 on 2024-05-26 04:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_ticket_reminder_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='subscribers',
            field=models.ManyToManyField(related_name='flight_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
