# Generated by Django 5.0.4 on 2024-05-26 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_flight_subscribers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='notified_subscribers',
            field=models.ManyToManyField(blank=True, related_name='notified_flight_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
